version: "3"
services:
  frontend:
    image: ghcr.io/int365-projectstreamingmusic/int365_frontend:latest
    container_name: frontend-dev
    ports:
        - 80:80
    networks:
       int372:
          ipv4_address: 172.10.0.2
networks:
  default:
    external:
       name: int372
  int372:
    external: true
