version: "3"
services:
  frontend:
    image: ghcr.io/int365-projectstreamingmusic/int365_frontend:latest
    container_name: frontend-dev
    ports:
        - 8080:80
#     networks:
#        int222:
#           ipv4_address: 172.10.0.2
# networks:
#   default:
#     external:
#        name: int222
#   int222:
#     external: true
