name: front-end Production
on:
  push:
    branches:
      - Production
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/int365-projectstreamingmusic/int365_frontend

  deploy:
    needs:
      - build
    runs-on: ubuntu-20.04
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME_PRO }}
        username: ${{ secrets.USERNAME_PRO }}
        key: ${{ secrets.PRIVATEKEY_PRO }}
        port: ${{ secrets.SERVERPORT_PRO }}
        script: | 
          cd frontend-pro
          sudo docker-compose down && sudo docker-compose pull
          sudo docker-compose up -d 
          sudo docker image prune -af
