name: front-end Develop
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
    with:
        node-version: 16
      - run: yarn install
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ghcr.io/int365-projectstreamingmusic/int365_frontend

  # deploy:
  #   needs:
  #     - build
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.HOSTNAME }}
  #       username: ${{ secrets.USERNAME }}
  #       key: ${{ secrets.PRIVATEKEY }}
  #       port: ${{ secrets.SERVERPORT }}
  #       script: | 
  #         cd ./dev/front-end/
  #         sudo docker-compose pull
  #         sudo docker-compose up -d 
  #         sudo docker image prune -af
